apiVersion: v1
kind: Pod
metadata:
  name: org-policy
  namespace : platform_security
spec:
  containers:
    - command:
        - sleep
        - "3600"
      image: busybox
      name: prisma-policy