apiVersion: v1
kind: Pod
metadata:
  name: sentinel-policy
  namespace : platform-security
spec:
  containers:
    - command:
        - sleep
        - "3600"
      image: busybox
      name: sentinel-policy